:source-highlighter: highlight.js

====
[.text-center]
**WIP** +
This section is a preview of the next milestone +
as such
it is incomplete, subject to change and may contain errors.
====

== Overview
This projet provides a validation framework for various implementations of PMT in various languages.
The primary targeted languages are:

* C,
* go,
* rust,
* typescript,
* python,
* zig.

The solution is extensible to other languages.

=== Definitions
Validating an implementation of a PMT involves three actors:

* The PMT implementation to be validated: _Implementation_ (for short),
* The validation framework: _Framework_,
* A test runner implemented in the same language as the PMT implementation to be tested: *Runner*.

==== _Implementation_ role
State of the art implementation of the PMT in the targeted language.

==== _Framework_ role
Offer an uniform way to execute operations over an _Implementation_ and validate its states.

==== _Runners_ role [[runners_role]]
Glues the _Framework_ and the _Implementation_. Its role is to:

* initialize the _Implementation_,
* request test instructions from the _Framework_,
* call the _Implementation_ methods accordingly to test instructions then pass the result back to the _Framework_.


== Design considerations
=== Languages interoperability
Generally, languages offer interoperability with other language with via the so called `FFI` foreign function interface.
`FFI` is closely related to the language memory model and many low level details like function arguments passing for function calls, etc.

The defacto standard for `FFI` is the `C` ABI which literarily means that all languages have to pass (and retrieve) arguments to(from) functions the `C` way and organize struct fields the `C` way (to name few).

Given that the `C` language has no memory management, allocated objects have to be manually freed to prevent memory leak. Language with a garbage collector

ABI has an impact over API. API in `C` are provided through so called `.h` files that defines `structs`, `enum` and functions signatures.


Here are some details for each targeted languages:

* C: obviously `C` uses the `C` ABI. In order to use a library build for interoperability with `C` a client only need the binary of that library and ideally its associated `.h`. Provided those two elements
* go,
* rust,
* typescript,
* python,
* zig.


==== _Implementation_
By definition a PMT _Implementation_ defines its API, the set of operations to interact with the tree. From an implementation to another that set of operations may vary, see [main document](./main.md) for a comparison between known implementations.
Because of those variations in operation sets some test cases may fail for some and succeed for others.

==== _Framework_
The _Framework_ is implemented in Rust.
It is delivered as a library that exposes its interfaces with the `C` ABI in order to be interoperable with as many language as possible.


==== _Runners_ and bindings
For _Runners_ to call the _Framework_ we also provide thin bindings to C for go, python and zig.
The Rust _Implementation_ can obviously go the native way.

For the TypeScript _Implementation_ using a `wasm` interface was envisioned. That would have imposed some constraints upon the _Framework_ (most notably being `no-std`). Thanks to https://deno.com/[Deno] (a JS/TS runtime) it is possible call Rust fonction natively through https://docs.deno.com/runtime/manual/runtime/ffi_api[ffi] and keep the same logic for all targeted implementation.




## Tests workflow
As said in <<runners_role, _Runners_ role>>, the test workflow is implemented by the _Runners_.
_Runners_ implementations are implemented in the same language as the _Implementation_. That leaves room for more flexibility.

_Runners_ take the form of this pseudo code (Rust):
[source,rust]
----
pub fn run_test(implementation, framework, test_case) {
    commands = framework.get_commands(test_case);
    for command in commands {
        run_command(command, implementation);
    }
}

pub fn run_all_test(framework) {
    tests = framework.get_all_tests();
    for test in tests {
        run_test(implementation, framework, test)
    }
}
----



The _Framework_ provides a set of commands to be executed on the target _Implementation_.
Each command should be implemented in the target language to execute the corresponding operation on the _Implementation_. (Golang example)
[source, go]
----
func run_command(command *C.Command, tree *trie.Trie) {
	/// TODO : implement each command who can be executed on the trie
	switch command.id {
	case C.Insert:
		panic("Insert not implemented")
	case C.Remove:
		panic("Remove not implemented")
	case C.CheckRootHash:
		panic("CheckRootHash not implemented")
	case C.Get:
		panic("Get not implemented")
	case C.Contains:
		panic("Contains not implemented")
	}
}
----

Implementation example :
TBD

// [source,go]
// ----
// include::../go/src/main.go[lines=5..10]
// ----

// * file://../go/src/main.go#43[Golang]
// * file://../python/main.py[Python]
// * file://../rust/src/command_interpreter.rs[Rust]
// * file://../typescript/deno/main.ts[TypeScript]
// * file://../c/src/main.c[C]
// * file://../zig/src/main.zig[Zig]

Test case example :
[source,yaml]
----
include::../scenario/3.yml[]
----

## Write your runner
## Implement the interface / trait that glued your implementation with the test framework

## Resources

### Test grammar

[source]
----
<yaml_file> ::= <directive>? <action>*

<directive> ::= "# yaml-language-server: $schema=./schema.json"

<action> ::= "- insert:" <insert_action>
           | "- check_root_hash:" <check_root_hash_action>
           | "- get:" <get_action>
           | "- contains:" <contains_action>
           | "- remove:" <remove_action>

<insert_action> ::= "key:" <key_array> "\n" "value:" <string_value>

<check_root_hash_action> ::= "expected_value:" <string_value>

<get_action> ::= "key:" <key_array> "\n" "expected_value:" <string_value>

<contains_action> ::= "key:" <key_array> "\n" "expected_value:" <boolean>

<remove_action> ::= "key:" <key_array>

<key_array> ::= "[" <integer> ("," <integer>)* "]"

<string_value> ::= <hexadecimal_value> | <decimal_value>

<hexadecimal_value> ::= "0x" <hex_digits>

<decimal_value> ::= <digit>+

<boolean> ::= "true" | "false"

<integer> ::= <digit>+

<hex_digits> ::= <hex_digit>+

<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<hex_digit> ::= <digit> | "a" | "b" | "c" | "d" | "e" | "f" | "A" | "B" | "C" | "D" | "E" | "F"
----